#!/usr/bin/python

import os
import re
import sys


X_axis = {
    'enable':      'D7',
    'dir':         'F1',
    'step':        'E4',
    'timer':       '3',
    'pulse':       '3B',
}

Y_axis = {
    'enable':      'F2',
    'dir':         'F7',
    'step':        'B5',
    'timer':       '1',
    'pulse':       '1A',
}

Z_axis = {
    'enable':      'K0',
    'dir':         'L1',
    'step':        'L3',
    'timer':       '5',
    'pulse':       '5A',
}

P_axis = {
    'enable':      None,
    'dir':         None,
    'step':        'H4',
    'timer':       '4',
    'pulse':       '4B',
}

axes = (('x', X_axis), ('y', Y_axis), ('z', Z_axis), ('p', P_axis))


defs = [
    'DDR%_enable',
    'DD%n_enable',
    'DDR%_dir',
    'DD%n_dir',
    'DDR%_step',
    'DD%n_step',
    None,

    'PORT%_enable',
    'PORT%n_enable',
    'PORT%_dir',
    'PORT%n_dir',
    'PORT%_step',
    'PORT%n_step',
    None,

    'TCCR%A',
    'COM%x1_pulse',
    'COM%x0_pulse',
    'WGM%1',
    'WGM%0',
    None,

    'TCCR%B',
    'CS%2',
    'CS%1',
    'CS%0',
    'WGM%3',
    'WGM%2',
    None,

    'TCNT%',
    None,

    'OCR%x_pulse',
    'ICR%',
    None,

    'TIMSK%',
    'TOIE%',
    None,

    'TIFR%',
    'TOV%',
    None,

    'TIMER%_OVF_vect',
    ]


def format_def(d, axis, map):
    sym = d.replace('%', axis, 1)
    defin = d
    for k, v in map.iteritems():
        if k in d:
            if v is None:
                return [sym]
            defin = re.sub(r'_[a-z]+', '', defin)
            defin = defin.replace('%n', v)
            defin = defin.replace('%x', v)
            defin = defin.replace('%', v[0])
    defin = defin.replace('%', map['timer'], 1)
    return sym, defin


def axis_defs(axis, map):
    return [format_def(d, axis, map) if d else None for d in defs]


def defs_by_axis():
    """return a dictionary mapping each axis to its list of definitions."""
    return dict((axis, axis_defs(axis, map)) for axis, map in axes)


def emit(all_defs):
    sym_width = max(len(d[0]) for axis in all_defs for d in all_defs[axis] if d)

    script = os.path.basename(sys.argv[0])
    ppsym = 'PIN_DEFS_INCLUDED'

    print '#ifndef', ppsym
    print '#define', ppsym
    print
    print '/* Automatically generated by %s; do not edit. */' % sys.argv[0]
    print
    for axis in (axis for axis, map in axes):
        print '/* %s Axis Definitions */' % axis.upper()
        for d in all_defs[axis]:
            if d is None:
                print
            elif len(d) == 1:
                print '/* undef %s */' % (d[0],)
            else:
                print '#define %-*s %s' % (sym_width, d[0], d[1])
        print
    print '#endif /* !%s */' % ppsym


if __name__ == '__main__':
    emit(defs_by_axis())
