#ifndef PIN_DEFS_INCLUDED
#define PIN_DEFS_INCLUDED

/* Automatically generated by gen_pin_defs.py; do not edit. */

/* X Axis Definitions */
#define DDRx_enable     DDRD
#define DDxn_enable     DDD7
#define DDRx_dir        DDRF
#define DDxn_dir        DDF1
#define DDRx_step       DDRE
#define DDxn_step       DDE4

#define PORTx_enable    PORTD
#define PORTxn_enable   PORTD7
#define PORTx_dir       PORTF
#define PORTxn_dir      PORTF1
#define PORTx_step      PORTE
#define PORTxn_step     PORTE4

#define TCCRxA          TCCR3A
#define COMxx1_pulse    COM3B1
#define COMxx0_pulse    COM3B0
#define WGMx1           WGM31
#define WGMx0           WGM30

#define TCCRxB          TCCR3B
#define CSx2            CS32
#define CSx1            CS31
#define CSx0            CS30
#define WGMx3           WGM33
#define WGMx2           WGM32

#define TCNTx           TCNT3

#define OCRxx_pulse     OCR3B
#define ICRx            ICR3

#define TIMSKx          TIMSK3
#define TOIEx           TOIE3

#define TIFRx           TIFR3
#define TOVx            TOV3

#define TIMERx_OVF_vect TIMER3_OVF_vect

/* Y Axis Definitions */
#define DDRy_enable     DDRF
#define DDyn_enable     DDF2
#define DDRy_dir        DDRF
#define DDyn_dir        DDF7
#define DDRy_step       DDRB
#define DDyn_step       DDB5

#define PORTy_enable    PORTF
#define PORTyn_enable   PORTF2
#define PORTy_dir       PORTF
#define PORTyn_dir      PORTF7
#define PORTy_step      PORTB
#define PORTyn_step     PORTB5

#define TCCRyA          TCCR1A
#define COMyx1_pulse    COM1A1
#define COMyx0_pulse    COM1A0
#define WGMy1           WGM11
#define WGMy0           WGM10

#define TCCRyB          TCCR1B
#define CSy2            CS12
#define CSy1            CS11
#define CSy0            CS10
#define WGMy3           WGM13
#define WGMy2           WGM12

#define TCNTy           TCNT1

#define OCRyx_pulse     OCR1A
#define ICRy            ICR1

#define TIMSKy          TIMSK1
#define TOIEy           TOIE1

#define TIFRy           TIFR1
#define TOVy            TOV1

#define TIMERy_OVF_vect TIMER1_OVF_vect

/* Z Axis Definitions */
#define DDRz_enable     DDRK
#define DDzn_enable     DDK0
#define DDRz_dir        DDRL
#define DDzn_dir        DDL1
#define DDRz_step       DDRL
#define DDzn_step       DDL3

#define PORTz_enable    PORTK
#define PORTzn_enable   PORTK0
#define PORTz_dir       PORTL
#define PORTzn_dir      PORTL1
#define PORTz_step      PORTL
#define PORTzn_step     PORTL3

#define TCCRzA          TCCR5A
#define COMzx1_pulse    COM5A1
#define COMzx0_pulse    COM5A0
#define WGMz1           WGM51
#define WGMz0           WGM50

#define TCCRzB          TCCR5B
#define CSz2            CS52
#define CSz1            CS51
#define CSz0            CS50
#define WGMz3           WGM53
#define WGMz2           WGM52

#define TCNTz           TCNT5

#define OCRzx_pulse     OCR5A
#define ICRz            ICR5

#define TIMSKz          TIMSK5
#define TOIEz           TOIE5

#define TIFRz           TIFR5
#define TOVz            TOV5

#define TIMERz_OVF_vect TIMER5_OVF_vect

/* P Axis Definitions */
/* undef DDRp_enable */
/* undef DDpn_enable */
/* undef DDRp_dir */
/* undef DDpn_dir */
#define DDRp_step       DDRH
#define DDpn_step       DDH4

/* undef PORTp_enable */
/* undef PORTpn_enable */
/* undef PORTp_dir */
/* undef PORTpn_dir */
#define PORTp_step      PORTH
#define PORTpn_step     PORTH4

#define TCCRpA          TCCR4A
#define COMpx1_pulse    COM4B1
#define COMpx0_pulse    COM4B0
#define WGMp1           WGM41
#define WGMp0           WGM40

#define TCCRpB          TCCR4B
#define CSp2            CS42
#define CSp1            CS41
#define CSp0            CS40
#define WGMp3           WGM43
#define WGMp2           WGM42

#define TCNTp           TCNT4

#define OCRpx_pulse     OCR4B
#define ICRp            ICR4

#define TIMSKp          TIMSK4
#define TOIEp           TOIE4

#define TIFRp           TIFR4
#define TOVp            TOV4

#define TIMERp_OVF_vect TIMER4_OVF_vect

#endif /* !PIN_DEFS_INCLUDED */
